### PR TITLE
Proposed fix for "Edit readme" is missing in GNS3 GUI. #2854

### PR DESCRIPTION
**Pull request by fatoms**
Reverted removal of main window menu item and restored attribute on topology object to support editing of the readme.

This also includes updated py files from changes to TAB order in "Tab Order in Preferences and Project Dialog #2872", Can they can be included in this pull request or should they be a separate request?

### CODE REVIEW

**Comment by fatoms** [comment]
Does this not fit your plans for the read-me feature ?

**Comment by grossmj** [comment]
The problem is we want the readme to be handled on server side. Currently, the readme feature would only work for local projects, not remote ones.

**Comment by grossmj** [comment]
Sorry, we will add the readme feature back in a later version. We have highest priorities now.

**Comment by b-ehlers** [comment]
Just integrated this patch (without the TAB order changes) into my local GNS3, it works fine.

> The problem is we want the readme to be handled on server side. Currently, the readme feature would only work for local projects, not remote ones.

@grossmj I'm puzzled by your comment. I tested this patch with a remote main server and it's working fine. "Edit readme" gets/puts README.txt from the controller by using `/v2/projects/{project_id}/files/README.txt`, why shouldn't that work with a remote controller?

**Comment by grossmj** [comment]
You are right, I was a bit quick to answer this PR. Actually, we did it to edit the readme for for exporting projects: https://github.com/GNS3/gns3-gui/commit/6787982408284c68fdcc7bf94470aef57223d7c5

**Comment by b-ehlers** [comment]
Maybe @fatoms can separate the TAB order changes from this PR into a new one. The TAB order changes are addressing a different issue.

**Comment by fatoms** [comment]
I have reverted the Tab Order related changes but still have the conflict in the generated file main_window_ui.py.

**Comment by grossmj** [comment]
Thanks a lot for this contribution and sorry it took us time to merge it.

I have generated the missing MainWindow Ui file on the master branch.

**Pull request merged**
