### PR TITLE
UI for settings image directories

### PR DESCRIPTION
**Pull request by noplay**
I propose to store additional image directories in a separate variable: additional_images_path as a string separate by a : like $PATH

Ref https://github.com/GNS3/gns3-server/issues/546

image

### CODE REVIEW

**Comment by grossmj** [comment]
Why don't we replace images_path by just an image_paths instead?

**Comment by grossmj** [comment]
Also, there is this error:

```
Traceback (most recent call last):
  File "/home/grossmj/PycharmProjects/gns3-gui/gns3/pages/general_preferences_page.py", line 117, in _imagesPathSlot
    directory = local_server["images_path"]
TypeError: 'LocalServer' object is not subscriptable
```

**Comment by noplay** [comment]
I was thinking that image_paths is the path were GNS3 will copy/download images by default

**Comment by grossmj** [comment]
It is more an Ui thing. We could have a list with one path selected by default.

**Comment by noplay** [comment]
You mean keep the list of image directories and replace the default image location by a listbox using this list?

**Comment by grossmj** [comment]
That could do it or have a button to make one of the path in the list of image directory the default path (which would be indicated in the list).

**Comment by grossmj** [comment]
Actually this is good like that.

**Pull request merged**
