### PR TITLE
Display an overlay popup with log messages

### PR DESCRIPTION
**Pull request by noplay**
This PR add a new way (the target is to hide by default the console at bottom) to display the error, warning and info. They are in an overlay popup to make them more visual. 

* If you click on messages they are hidden. 
* Maximum 3 message is display on screen
* After a delay the messages are hidden (different by level)
* This a PR for GNS3 2.1

You can test the notif by typing in the console:
```
log info test
log warning test
log error test
```

It will probably need to be adjust, especially I think we will need to log less info messages.

Ref #1334

### CODE REVIEW

**Comment by grossmj** [comment]
I would add an option to deactivate this because some users may find it annoying.

**Comment by noplay** [comment]
Checkbox added

**Comment by grossmj** [comment]
Ok to merge once conflict is solved.

**Comment by noplay** [comment]
Merged

**Pull request merged**
