### PR TITLE
Fix issues when Wifi is turned off

### LINKED ISSUE #2104: Hibernation/Network modified issues
While reopening my laptop from hibernation I can see the following errors. Not a real problem because I could keep using the current project.

```
Can't get settings from controller
Error while getting appliance templates list: Network session error.
Error while getting appliance list: Network session error.
Error while getting compute list: Network session error.
Network session error.
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
Error while listing project: Network session error.
Error while listing links: Network session error.
Error while listing drawings: Network session error.
Can't get settings from controller
Can't get settings from controller
```

### PR DESCRIPTION
**Pull request by noplay**
We dynamically change to the best available network when the network is lost.

Fix #2104

### CODE REVIEW

**Comment by noplay** [comment]
Need to be test on multiple computer to be sure it's work.

Test is simple.
* Open GNS3 with Wifi on
* Create a topology
* Move node
* Turn wifi off
* Move node

**Comment by grossmj** [comment]
It works on my Linux but I got many error messages:

```
"No such interface 'org.freedesktop.DBus.Properties' on object at path /"
"No such interface 'org.freedesktop.DBus.Properties' on object at path /org/freedesktop/NetworkManager/ActiveConnection/5"
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
Can't get settings from controller
Error while getting appliance templates list: Network session error.
Error while getting appliance list: Network session error.
Error while getting compute list: Network session error.
Network session error.
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
Error while listing project: Network session error.
Error while listing links: Network session error.
Error while listing drawings: Network session error.
Can't get settings from controller
Error while getting compute list: Network session error.
Can't get settings from controller
Can't get settings from controller
Can't get settings from controller
Network session error.
Error while getting appliance templates list: Network session error.
Error while getting appliance list: Network session error.
Error while getting compute list: Network session error.
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
Error while listing project: Network session error.
Error while listing links: Network session error.
Error while listing drawings: Network session error.
```

**Comment by noplay** [comment]
But after it's work? I have seen some latency before we got the signal.

**Comment by grossmj** [comment]
Yes it worked the first time, I could still use the project again however the second time GNS3 segfaulted :(

**Comment by noplay** [comment]
Is it better ? I try to avoid multiple error dialogs.

**Comment by grossmj** [comment]
This looks better, I only got that in the GNS3 console when switching off Wifi:

```
=> Can't get settings from controller
Error while getting appliance templates list: Network session error.
Error while getting appliance list: Network session error.
Error while getting compute list: Network session error.
****** Exception detected, traceback information saved in /home/grossmj/.config/GNS3/exceptions.log ******

PLEASE REPORT ON https://www.gns3.com

Traceback (most recent call last):
  File "/home/grossmj/PycharmProjects/gns3-gui/gns3/topology.py", line 219, in _projectCreationErrorSlot
    self._project.project_creation_error_signal.disconnect(self._projectCreationErrorSlot)
AttributeError: 'NoneType' object has no attribute 'project_creation_error_signal'

Error while listing project: Network session error.
Error while listing links: Network session error.
Error while listing drawings: Network session error.
Can't get settings from controller
Error while getting compute list: Network session error.
Can't get settings from controller
Can't get settings from controller
```

**Comment by grossmj** [comment]
Resuming from sleep mode I still get that annoying "Connect to server" dialog.

sleep_mode

**Comment by noplay** [comment]
Should be better. Seem the signal could happen even if we already change
the project

**Comment by grossmj** [comment]
I don't get the exception anymore however if I try a second time to switch off Wifi I got the following result:

second_try

**Comment by noplay** [comment]
I don't see what we can do to improve. It's Qt internals that spam the warning until it emit the signal and allow us to switch the network :(

**Comment by grossmj** [comment]
That will do until Qt has better support for this.

**Pull request merged**
