### PR TITLE
2.2 py.test test_local_config.py failing

### PR DESCRIPTION
**Pull request by jnatschev**
when running py.test it was failing test_local_config.py, function test_migrateOldConfigOSX. Looking at what is being tested and what is on disk, i found a difference.

in the file line 122:
assert os.path.exists(str(tmpdir / '.config' / 'GNS3'))
change line 122 to:
assert os.path.exists(str(tmpdir / '.config' / 'GNS3' / '2.2'))

in the file line 123:
assert os.path.exists(str(tmpdir / '.config' / 'GNS3' / 'hello'))
change line 123 to:
assert os.path.exists(str(tmpdir / '.config' / 'GNS3' / '2.2' / 'hello'))

in the file line 130:
assert os.path.exists(str(tmpdir / '.config' / 'GNS3' / 'hello'))
change line 130 to:
assert os.path.exists(str(tmpdir / '.config' / 'GNS3' / '2.2' / 'hello'))

in the file line 131:
assert not os.path.exists(str(tmpdir / '.config' / 'GNS3' / 'world'))
change line 131 to:
assert not os.path.exists(str(tmpdir / '.config' / 'GNS3' / '2.2' / 'world'))

i made the changes and ran py.test again and now the failure has gone away.

### CODE REVIEW

**Comment by jnatschev** [comment]
also. just remembered. there is a deprecation warning on the gns3/appliance.py file.
i modified two lines:
line 22 - import collections
line 22 + import collections.abc

line 33 - class Appliance(collections.Mapping):
line 33 + class Appliance(collections.abc.Mapping):

**Comment by jnatschev** [comment]
also. the reason i cloned is because i was hoping i could help with my "enhancement" request #3008 
can you let me know where in the code i can find the spot that initiates the project window at startup please?
it'll be helpful to read and understand how that all works. i'll try to stop it to start with. then get it to open again. then i'll look at adding a test to see if the config file can have something like:
project dialog on startup = True/False
probably under "MainWindow" or wherever you think it is best for it go...

**Comment by grossmj** [comment]
I have fixed the tests. Thanks for catching these errors :+1: I will review your request in https://github.com/GNS3/gns3-gui/issues/3008 soon.

**Comment by jnatschev** [comment]
cool. thanks. i'd never participated like this before. great to see it work first hand like this.

**Pull request closed without merging**
