### PR TITLE
Accurate upload progress dialogs for large files

### PR DESCRIPTION
**Pull request by ziajka**

### CODE REVIEW

**Comment by grossmj** [comment]
On Linux: the progress bar stays a 50% for while and then completes when installing the CentOS appliance which has an image of around 4 GB.

centos_upload

**Comment by ziajka** [comment]
Good to know. Haven't seen that on Linux. Windows was fine?

**Comment by ziajka** [comment]
This issue was only upload via compute 'cause of current implementation of multi-query for progress. It should be fine now.

**Comment by grossmj** [comment]
All is good now :+1:

**Pull request merged**
