### PR TITLE
Allow to import unknow files via GNS3A

### LINKED ISSUE #980: Allow to import unknow files via GNS3A
Andrew say that:

> When using an appliance template to install IOS routers, I have binaries other than the defaults found in the template, so it refuses to import them. Some text saying "For now, you'll need to install this IOS router manually" would be good. 

But it can be better to allow user to import not recognized image in case of the manufacturers release a new image.

### PR DESCRIPTION
**Pull request by noplay**
Fix #980

### CODE REVIEW

**Comment by grossmj** [comment]
When installing the appliance without importing an unknown file.

```
****** Exception detected, traceback information saved in /home/grossmj/.config/GNS3/exceptions.log ******

PLEASE REPORT ON https://www.gns3.com

Traceback (most recent call last):
  File "/home/grossmj/PycharmProjects/gns3-gui/gns3/dialogs/appliance_wizard.py", line 419, in validateCurrentPage
    if not self._appliance.is_version_installable(version["name"]):
  File "/home/grossmj/PycharmProjects/gns3-gui/gns3/registry/appliance.py", line 150, in is_version_installable
    self.search_images_for_version(version)
  File "/home/grossmj/PycharmProjects/gns3-gui/gns3/registry/appliance.py", line 130, in search_images_for_version
    raise ApplianceError("File {} with checksum {} not found for {}".format(image["filename"], image["md5sum"], appliance["name"]))
KeyError: 'md5sum'
```

**Comment by noplay** [comment]
Fixed

**Comment by grossmj** [comment]
The view isn't updated after importing the file. It always shows 0.0B.

**Comment by noplay** [comment]
Updated and I add a md5 sum

**Pull request merged**
