### PR TITLE
Allow drawing lines

### LINKED ISSUE #997: Drawing lines
I think this falls under the caption, "Nice to Have."  I have been developing Cisco routing and switching laps in GNS3 for which drawing lines would be very helpful.  I am currently using the "draw a rectangle" feature and am collapsing the box so it looks like a line, which works okay but makes it difficult to move around the screen easily.  Below is a screen shot of Lab 2-1 EIGRP Load Balancing  I recently completed that shows a few lines.
screenshot

Thanks,

Jim

### PR DESCRIPTION
**Pull request by noplay**
This PR allow user to draw lines. For the moment an icon is missing I don't know if we have something in stock.

A good news this PR is only client side, no need to update the server. This mean the drawing API  build on top of SVG work well.

Fix #997

### CODE REVIEW

**Comment by grossmj** [comment]
I will work on icons later. Also, I noticed some strange behaviour when resizing a line.

**Comment by grossmj** [comment]
I think we are almost there on this one. However, I find it almost impossible to move a vertical line. Also, I noticed some strange behaviour when resizing or dropping a line.

**Comment by noplay** [comment]
I will try to improve vertical

**Comment by noplay** [comment]
I just improved vertical line

**Comment by grossmj** [comment]
Seems to work well :+1:

**Pull request merged**
