### PR TITLE
Show a summary with server usages

### LINKED ISSUE #963: Display stats about running servers
Display the stats of server (CPU usage, Memory usage...)

Stats from here https://github.com/GNS3/gns3-server/issues/252

### PR DESCRIPTION
**Pull request by noplay**
Fix #963

capture d ecran 2016-01-26 a 18 31 51

Not sure if we should merge it today

### CODE REVIEW

**Comment by grossmj** [comment]
:+1: ok to merge (there is a conflict to solve)

**Comment by ehlers** [comment]
Really nice, but as the "Servers Summary" isn't available in "View / Docks", you can't get it back after (accidentally) closing this dock.

**Comment by ehlers** [comment]
An additional idea: Currently it looks, as if all servers are initially down. Maybe it's better to set the initial server status to unknown (e.g. yellow). After successful connection set it to green (you already do that) and after an unsuccessful connection set it to red.

**Comment by grossmj** [comment]
Good points!

**Comment by noplay** [comment]
Ticket open #965 and #966

**Pull request merged**
