### PR TITLE
Bugfix 1095

### PR DESCRIPTION
**Pull request by ziajka**

### CODE REVIEW

**Comment by ziajka** [comment]
References #2124 and #712

**Comment by ziajka** [comment]
Name of this PR may be confusing.

**Comment by noplay** [comment]
Sound good !

**Comment by noplay** [comment]
You can close the related issues and update:
https://drive.google.com/open?id=1_xhTp3fAzIKfE6ujQ-P1_CCaKuhgbQblOT7uITr91qI

**Comment by grossmj** [comment]
This PR introduces errors when loading projects:

```Invalid data in topology file: Additional properties are not allowed ('snap_to_grid', 'show_grid', 'show_layers', 'zoom', 'show_interface_labels' were unexpected) in schema```

**Comment by noplay** [comment]
I don't have this error. Do you have the last server code ?

**Comment by grossmj** [comment]
I got this errors while on the filters PRs (gui and server). Maybe something hasn't been merged to the server side.

**Comment by noplay** [comment]
The filter PR branch was made before. The project made with last 2.1 will not be compatible and will not be loaded by the server. I recommend to test with new project

**Comment by grossmj** [comment]
That's what I ended up doing.

**Pull request merged**
