### PR TITLE
EthernetSwitch: Allow to choose ethertype for QinQ outer tag.

### PR DESCRIPTION
**Pull request by Bevaz**
This patch makes possible to chose ethertype for Q-in-Q outer tag.
Possible values are: 0x8100 (default), 0x9100, 0x9200, 0x88A8.

Related pull requests:
GNS3/dynamips#66
GNS3/gns3-server#297

### CODE REVIEW

**Comment by grossmj** [comment]
Hi Bevaz,

Thanks for your Pull Request. We will review it as soon as possible, all of us are currently away or in holidays ;)

In the meantime, it would be great if you can sign our CLA at https://github.com/GNS3/cla

Thanks a lot.

**Comment by Bevaz** [comment]
Signed GNS3/cla#6

**Comment by noplay** [comment]
The CLA is validated.

**Comment by grossmj** [comment]
Merged in unstable: https://github.com/GNS3/gns3-gui/commit/1216882e89d1adb5e11a026a060968b3fc9ca26a

**Pull request closed without merging**
