### PR TITLE
Move duplicate code to node.py

### PR DESCRIPTION
**Pull request by noplay**
Hi @grossmj ,

During my integrations of iou in the server i have discover large portions of duplicate in code and tests. I have move this code to node.py.

The moved code is:
* start
* stop
* reload
* addNio
* deleteNio
* allocateUdpPort

Also i discover that we use on server side the name adapter for virtualbox and port for VPCS. But on client side it's the same thing: a port.

### CODE REVIEW

**Comment by grossmj** [comment]
Hi @noplay

I agree this is duplicated code, however there is a major issue in classes like MainWindow and GraphicsView (and maybe somewhere else too): some graphical functions depends on the location of the method because some devices cannot be started (Dynamips switches are always on), suspended (VPCS for instance), have packets capture etc. 

For instance in the device contextual menu: https://github.com/GNS3/gns3-gui/blob/rest-api/gns3/graphics_view.py#L676

you have many references like hasattr(item.node(), "start") to select the entries to add to the menu depending on what actiopn a device support. I agree this isn't great architecture but we have to find an alternative solution if we want to have all the methods in nodes.py

**Comment by noplay** [comment]
I understand. Perhaps we can move this common code to VM class which is a subclass of Node.

**Comment by noplay** [comment]
It's refactored to use a VM class

**Comment by grossmj** [comment]
Seems all good :)

**Pull request merged**
