### PR TITLE
Ask the user to stop device before closing

### PR DESCRIPTION
**Pull request by noplay**
This should avoid some problems with ghost process remaining.

Ref #1088

### CODE REVIEW

**Comment by grossmj** [comment]
Cannot close GNS3 when a topology has not been saved ;)

**Comment by noplay** [comment]
Fixed

**Comment by grossmj** [comment]
Why don't we stop the nodes ourselves? Something like:

```
        if running_node:
            reply = QtWidgets.QMessageBox.warning(self, "GNS3", "A device is still running, would you like to continue?",
                                                           QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No)
            if reply == QtWidgets.QMessageBox.Yes:
                for node in topology.nodes():
                    if hasattr(node, "stop") and node.status() == Node.started:
                        node.stop()
                return True
            else:
                return False
```

**Comment by noplay** [comment]
Problem if we do that we don't wait for everything to exit (signal hell...
).

**Pull request merged**
