### PR TITLE
Allow to export a zip with debug informations

### LINKED ISSUE #408: GUI extension: Create File with debugging information
How about a GUI function to create a (zip) file with the key information for debugging an issue.

This could be:
- System information (OS, OS version, GNS3 version, ...)
- GUI log
- Server log
- Topology (.GNS3 file)
- Topology as PNG file

It should be small, as otherwise people with a poor internet connectivity will have problems to upload this file.

Then we "just" have to convince the users, that issues without these informations get a lower priority.

### PR DESCRIPTION
**Pull request by noplay**
The zip contains:
* informations about the system, network and processus
* configuration
* log
* current .gns3 and screenshoot

Hope it will help to solve issues with can't connect to
http://127.0.0.1:8000

Fix #408

### CODE REVIEW

**Comment by noplay** [comment]
Bug 777 :)

**Comment by ehlers** [comment]
Looks good for me, just one comment:

Just had a look at the diffs, so not sure about it. But for me it seems, that it exports the project file from disk. That's not necessarily the actual state of the project. No big deal, just tell the user to save the project before creating the debugging file.

**Comment by noplay** [comment]
You are right I will add a warning asking user to save project

**Comment by noplay** [comment]
Done

**Pull request merged**
