### PR TITLE
Do not run import / export of project in seperate thread

### LINKED ISSUE #2008: Warning when exporting portable project
```
QObject: Cannot create children for a parent that is in a different thread.
(Parent is HTTPClient(0x7fdb8f0394b0), parent's thread is QThread(0x7fdb8c922f20), current thread is QThread(0x7fdb909956b0)
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QNetworkAccessManager(0x7fdb8f03e5a0), parent's thread is QThread(0x7fdb8c922f20), current thread is QThread(0x7fdb909956b0)

### PR DESCRIPTION
**Pull request by noplay**
This trigger warning because you need to do the HTTP request
to the API from the main thread.

I also dropped some unused code in the import and export class.

Fix #2008

### CODE REVIEW

**Comment by grossmj** [comment]
This does not work on my Linux, no warning but the exported file is 0 bytes with a project including IOS and IOU devices.

**Comment by noplay** [comment]
Do you see the call to /export on the server?

If you curl the export it's work?
http://api.gns3.net/en/2.0/api/v2/controller/project/projectsprojectidexport.html

**Comment by grossmj** [comment]
I see the call but a 409 error is returned (which is not shown in the GUI).

```
2017-05-11 21:56:06 INFO helpers.py:480 172.16.45.1 - - [11/May/2017:13:56:06 +0000] "POST /v2/projects/6e5fb3ed-19d1-40af-a5f7-44d072395372/files//README.txt HTTP/1.1" 200 0 "-" "GNS3 QT Client v2.0.1dev1-50cca71"
2017-05-11 21:56:06 INFO helpers.py:480 172.16.45.1 - - [11/May/2017:13:56:06 +0000] "GET /v2/projects/6e5fb3ed-19d1-40af-a5f7-44d072395372/export?include_images=1 HTTP/1.1" 409 225 "-" "GNS3 QT Client v2.0.1dev1-50cca71"
```

I can see the reason with a little CURL investigation.

```
$ curl -i -X GET 'http://172.16.45.1:3080/v2/projects/6e5fb3ed-19d1-40af-a5f7-44d072395372/export'
HTTP/1.1 409 Conflict
Server: Python/3.5 GNS3/2.0.1dev1
X-Route: /v2/projects/{project_id}/export
Connection: close
Content-Type: application/json
Content-Length: 225
Date: Thu, 11 May 2017 14:00:20 GMT

{
    "message": "Topology could not be exported because the image /home/grossmj/GNS3/images/IOS/IOSv-L2.vmdk is not available. If you use multiple server, we need a copy of the image on the main server.",
    "status": 409
}
```

Errors should not be silently dropped in the GUI.

**Comment by grossmj** [comment]
This may be the result of another bug: I can boot the IOSv-L2 in that lab, looking in the node preferences I can see the image path is `/home/grossmj/GNS3/images/QEMU/IOSv-L2.vmdk`, where does the `/home/grossmj/GNS3/images/IOS/IOSv-L2.vmdk` path come from?

**Comment by grossmj** [comment]
I removed the QEMU node from my lab and I was able to export a portable project this time :)

**Comment by noplay** [comment]
Their is something weird we got similar bug report with a mismatch on the
image directory

**Comment by noplay** [comment]
It's look like https://github.com/GNS3/gns3-server/issues/1010 I reopen it

**Comment by noplay** [comment]
The 409 not display is fixe, we can merge and work on  GNS3/gns3-server#1010

**Comment by grossmj** [comment]
Confirmed.

**Pull request merged**
