### PR TITLE
Display the appliances in the application

### PR DESCRIPTION
**Pull request by noplay**
Ref #1045

Video demo:
https://www.youtube.com/watch?v=zmRM1iISynI

Server side:
https://github.com/GNS3/gns3-server/pull/888

### CODE REVIEW

**Comment by grossmj** [comment]
Exception when you right click on a device in the list:

```
****** Exception detected, traceback information saved in /home/grossmj/.config/GNS3/exceptions.log ******

PLEASE REPORT ON https://www.gns3.com

Traceback (most recent call last):
  File "/home/grossmj/PycharmProjects/gns3-gui/gns3/nodes_view.py", line 148, in mousePressEvent
    self._showContextualMenu()
  File "/home/grossmj/PycharmProjects/gns3-gui/gns3/nodes_view.py", line 192, in _showContextualMenu
    node_class = module.getNodeClass(node["class"])
KeyError: 'class'
```

**Comment by grossmj** [comment]
Using the filter to try to type "Cisco" on available appliances show this error multiple times.

filter_issue

**Comment by noplay** [comment]
Error fixed

**Comment by noplay** [comment]
Tests are green it's ready to be tested again.

**Pull request merged**
