### PR TITLE
Dissallow unknown extensions

### LINKED ISSUE #1490: gns3a import is not detected as GNSA file if the extension is not gns3a
If the file is not named .gns3a when using import appliance GNS3 will think this a topology.

image

A user got this error when opening 
cisco-asav.gns3a**.txt**

### PR DESCRIPTION
**Pull request by noplay**
This PR propose to allow GNS3 to open only file with a known extension

Fix #1490

### CODE REVIEW

**Comment by grossmj** [comment]
Can't we detect this by reading the file? For projects we should have "type" field set to "topology". Apparently we are missing something like that in .gns3a

**Comment by noplay** [comment]
Actually we have no special fields in .gns3a 

Problem is this field will not work for gns3project due to the use of zip file

**Comment by grossmj** [comment]
I really think we should detect valid files and this shouldn't based on the extension.

**Comment by noplay** [comment]
We can improve to check if it seem to be valid. But guessing the type of file based on the content without a magic seem dangerous to me. 

For example a .zip file could be a zipped IOS, an export of a gns3 project or something manually zipped by the user.

Also If a file is not named .gns3 we will need to fix that because the server will not be able find it in when scanning the folder.

We can also improve the GUI by removing the "All files" options from the open dialog. Preventing user opening an unknown file from the interface. It will be possible only by the command line or by associating the wrong file type to the application.

**Comment by noplay** [comment]
Because it's have bigger impact than expected  I rebased it on 2.0

**Comment by grossmj** [comment]
Do you still want this merged?

**Comment by noplay** [comment]
I don't see good reason to let user use unknown extension or invalid extension. 

We can improve the checks, to validate the file is correct. But it's easier if we don't try to guess the file type based on his content.

**Pull request merged**
