### PR TITLE
Add an appliance templates directory

### PR DESCRIPTION
**Pull request by noplay**
* Settings in general preferences to configure it
* When you import a gns3a the file is copy to this directory
* A filter my appliances is available

Fix https://github.com/GNS3/gns3-gui/issues/2133

### CODE REVIEW

**Comment by grossmj** [comment]
There is only one thing. I don't like the name "My available appliances" because it is confusing with the "Available appliances" entry. I would name that "Custom appliances" instead.

**Comment by grossmj** [comment]
Also, I got that exception when using the filter text box:

```
Traceback (most recent call last):
  File "/home/grossmj/PycharmProjects/gns3-gui/gns3/nodes_dock_widget.py", line 31, in _filterTextChangedSlot
    self.window().uiNodesView.refresh()
  File "/home/grossmj/PycharmProjects/gns3-gui/gns3/nodes_view.py", line 80, in refresh
    self.populateNodesView(self._current_category, self._current_search)
  File "/home/grossmj/PycharmProjects/gns3-gui/gns3/nodes_view.py", line 115, in populateNodesView
    if not appliance["builtin"] and not self._show_my_available_appliances:
KeyError: 'builtin'
```

**Comment by noplay** [comment]
Did you test with the corresponding server branch?  Because I don't replicate the crash.

**Comment by noplay** [comment]
Text fixed

**Comment by grossmj** [comment]
Yes, I am on both the correct the GUI & server branches

**Comment by grossmj** [comment]
Strangely I cannot reproduce the issue :( I don't know what went wrong.

**Pull request merged**
